# Generated by Django 5.1.4 on 2024-12-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-01 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default='No description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='title',
            field=models.CharField(default='Untitled Course', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='email',
            field=models.CharField(default='example@gmail.com', max_length=150),
        ),
        migrations.AddField(
            model_name='students',
            name='enrolled_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-01 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='name',
            field=models.CharField(default='Unnamed Student', max_length=50),
            preserve_default=False,
        ),
    ]
